//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string pName { get; set; }
        public double Kcal { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Carb { get; set; }
        public Nullable<double> Fats { get; set; }
    }
}
