//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int IDu { get; set; }
        public string Nick { get; set; }
        public string Pass { get; set; }
    
        public virtual ProdHistory ProdHistory { get; set; }
    }
}
